version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: go-train-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: frank900405
      POSTGRES_DB: goDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: go-train-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=localhost:6379
      - REDIS_PASSWORD= # 如果有密碼，請在此處設定
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
